# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
version: 2.1

jobs:
  daml:
    docker:
      - image: digitalasset/daml-sdk:0.13.41
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Dar
          command: daml build -o target/finlib.dar
      - run:
          name: Test Dar
          command: daml test --junit target/DarTests.xml
      - run:
          name: Save test results
          command: |
            mkdir -pv ~/test-results/daml
            find . -type f -regex ".*/target/.*DarTests.xml" -exec cp {} ~/test-results/daml/ \;
      - store_test_results:
          path: ~/test-results

workflows:
  Build and test:
    jobs:
      - daml
